version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: recs_postgres
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    container_name: recs_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    container_name: recs_api
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_URL: ${REDIS_URL}
      REGION: ${REGION}
    volumes:
      - ../apps/api:/app
      - ../infra:/infra
    command: ["bash", "-lc", "uvicorn app.main:app --host 0.0.0.0 --port ${API_PORT:-8000} --reload"]
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  recsys:
    build:
      context: ../services/recsys
      dockerfile: Dockerfile
    container_name: recs_recsys
    env_file:
      - ../.env
    environment:
      POSTGRES_HOST: postgres
      REDIS_URL: ${REDIS_URL}
      REGION: ${REGION}
    volumes:
      - ../services/recsys:/app
    command: ["bash", "-lc", "python -m worker"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    container_name: recs_web
    env_file:
      - ../.env
    environment:
      NEXT_PUBLIC_API_URL: http://api:8000
      NODE_ENV: development
    volumes:
      - ../apps/web:/app
    command: ["bash", "-lc", "pnpm install && pnpm dev"]
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_started

volumes:
  pgdata:
