from typing import Iterable, Optional, Dict, Any, Protocol

class Show(Dict[str, Any]): ...
class Provider(Protocol):
    name: str
    async def search(self, q: Optional[str]=None, limit: int=20) -> Iterable[Show]: ...
    async def popular(self, limit: int=20) -> Iterable[Show]: ...
