name: Auto Revert on Main Failure

on:
  workflow_run:
    workflows: ["CI"] # must match the name above
    types: [completed]

permissions:
  contents: write   # needed to push the revert commit
  issues: write     # to open an Issue with the logs

concurrency:
  group: autorevert-${{ github.event.workflow_run.head_sha }}

env:
  OPEN_ISSUE: "true"  # set to "false" to keep reverts silent

jobs:
  maybe_retry:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger one retry if first attempt
        if: ${{ github.event.workflow_run.run_attempt == 1 }}
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = context.payload.workflow_run.id;
            await github.request('POST /repos/{owner}/{repo}/actions/runs/{run_id}/rerun', {
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id
            });
            core.notice(`Re-run triggered for run ${run_id}`);

  revert:
    if: ${{ github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.head_branch == 'main' && github.event.workflow_run.run_attempt > 1 }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: refs/heads/main

      - name: Guard: skip if already a Revert or marked [skip-revert]
        id: guard
        run: |
          SHA='${{ github.event.workflow_run.head_sha }}'
          MSG="$(git show -s --format=%s "$SHA")"
          echo "HEAD SHA: $SHA"
          echo "Message: $MSG"
          if echo "$MSG" | grep -qiE '(^Revert\b|\[skip-revert\])'; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure git
        if: ${{ steps.guard.outputs.skip != 'true' }}
        run: |
          git config user.name "recs-app CI bot"
          git config user.email "actions@users.noreply.github.com"

      - name: Revert the failing commit
        if: ${{ steps.guard.outputs.skip != 'true' }}
        run: |
          set -e
          git fetch origin main
          git checkout -B main origin/main
          # Attempt revert of the failing head commit
          if ! git revert --no-edit '${{ github.event.workflow_run.head_sha }}'; then
            echo "revert_conflict=1" >> $GITHUB_ENV
          fi

      - name: Push revert
        if: ${{ steps.guard.outputs.skip != 'true' && env.revert_conflict != '1' }}
        run: git push origin HEAD:main

      - name: Open Issue with failure details
        if: ${{ env.OPEN_ISSUE == 'true' && steps.guard.outputs.skip != 'true' }}
        uses: actions/github-script@v7
        with:
          script: |
            const sha = context.payload.workflow_run.head_sha;
            const url = context.payload.workflow_run.html_url;
            const title = `Auto-revert: failing commit ${sha.substring(0,7)} on main`;
            const body = [
              `The CI workflow failed on main for commit \`${sha}\`.`,
              '',
              `Workflow run: ${url}`,
              '',
              (process.env.revert_conflict === '1'
                ? '**Revert encountered conflicts.** Manual fix needed.'
                : 'Revert pushed to `main`.'),
              '',
              'To opt out for a specific commit, include `[skip-revert]` in the commit message.'
            ].join('\\n');
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
            });
