name: build-offline-caches
on:
  workflow_dispatch:

jobs:
  python-wheels:
    name: Python wheels (macOS, Py 3.11)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Prepare wheel cache
        run: |
          python -m pip install --upgrade pip wheel setuptools packaging
          mkdir -p vendor/wheels
          if [ -f apps/api/requirements.txt ]; then
            python -m pip download -r apps/api/requirements.txt -d vendor/wheels
          fi
          # Safety set (runtime + build helpers + tests deps commonly used)
          python -m pip download -d vendor/wheels \
            fastapi starlette uvicorn "pydantic>=2" pydantic-core sqlalchemy sqlmodel \
            anyio h11 click requests python-dotenv prometheus-client \
            pytest pytest-asyncio httpx \
            setuptools wheel packaging
          tar -C vendor -czf vendor_wheels.tgz wheels
          shasum -a 256 vendor_wheels.tgz > vendor_wheels.tgz.sha256

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: vendor_wheels_macos_py311
          path: |
            vendor_wheels.tgz
            vendor_wheels.tgz.sha256

  pnpm-store:
    name: pnpm store (macOS, Node 20)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        run: npm i -g pnpm

      - name: Fetch pnpm store
        working-directory: apps/web
        run: pnpm fetch

      - name: Package store
        run: |
          STORE_DIR=$(cd apps/web && pnpm store path)
          mkdir -p vendor
          tar -czf vendor_pnpm_store.tgz -C "${STORE_DIR}" .
          shasum -a 256 vendor_pnpm_store.tgz > vendor_pnpm_store.tgz.sha256

      - name: Upload pnpm store artifact
        uses: actions/upload-artifact@v4
        with:
          name: vendor_pnpm_store_macos_node20
          path: |
            vendor_pnpm_store.tgz
            vendor_pnpm_store.tgz.sha256
