name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
  push:
    branches: [main]
jobs:
  test-and-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo OK
