name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  test-and-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo OK
