name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  test-and-health:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install API deps
        run: |
          if [ -f apps/api/requirements.txt ]; then
            python -m pip install -U pip wheel
            pip install -r apps/api/requirements.txt
          fi

      - name: Detect FastAPI app import
        id: detect
        shell: bash
        run: |
          APP_IMPORT=$(python - <<'PY'
import importlib
cands=[("apps.api.app.main","app"),("apps.api.app.__init__","app"),("apps.api.app.recs","app")]
for m,a in cands:
    try:
        mod=importlib.import_module(m)
        if hasattr(mod,a):
            print(f"{m}:{a}")
            break
    except Exception:
        pass
PY
          )
          echo "APP_IMPORT=$APP_IMPORT" >> "$GITHUB_ENV"

      - name: Healthcheck API
        shell: bash
        env:
          APP_IMPORT: ${{ env.APP_IMPORT }}
        run: |
          set -e
          if [ -n "$APP_IMPORT" ]; then
            python -m pip install uvicorn >/dev/null 2>&1 || true
            nohup python -m uvicorn "$APP_IMPORT" --host 127.0.0.1 --port 8000 >/dev/null 2>&1 & echo $! > app.pid
            end=$((SECONDS+60)); ok=0
            while [ $SECONDS -lt $end ]; do
              if curl -fsS http://127.0.0.1:8000/readyz >/dev/null 2>&1; then ok=1; break; fi
              sleep 2
            done
            if [ "$ok" -ne 1 ]; then echo "healthcheck failed"; kill $(cat app.pid) 2>/dev/null || true; exit 1; fi
            kill $(cat app.pid) 2>/dev/null || true
          else
            echo "APP_IMPORT not found; skipping"
          fi
